### ISSUE TITLE
MCT builds

### ISSUE THREAD

**Issue by asuanda** [wingtorres/coawst-conda#1]
Hello, I'm very appreciative of this repo. Very helpful! However, I am having some issues with the MCT build on MacOS. I can follow your suggestion for the work-around in the Makefile.conf and it builds, but then I cannot actually use the MCT for the Inlet coupled ROMS/SWAN test case. Have you had success with the other coupled model examples?

**Comment by wingtorres** [comment]
Hi there,

Glad you are getting use out of the repo! I made it mostly for myself and a collaborator, but great to see that it can help others. Can you give me more details about the problem you are having? Are you able to build the executable or does the problem occur when you call mpirun? I just tested a fresh install of COAWST (recently updated to 3.7) in a fresh conda environment and the Inlet_test/DiffGrid case compiles and runs fine. I did notice I had to make sure SCRATCH_DIR was defined in coawst.bash uncommenting a line or it would not compile. I also found that to avoid conflict with my other MPI installation I had to modify the $PATH environment variable. I'll update the readme.md, but let me know how it goes.

**Comment by asuanda** [comment]
Hello, yes - very helpful (I'm a new CONDA user, so this is great). The build worked fine for a COAWST example that was only running ROMS (the ducknc example). Executable created and runs. When I tried to build a coupled ROMS+SWAN example (inlet), coawst.bash would not complete the compiling process. I thought it was related to MCT. John Warner from USGS sent me a modified compiler file (attached) - it now works!
It does not look very different from the one in your repo - still trying to parse the differences...
[Darwin-gfortran.mk.txt](https://github.com/wingtorres/coawst-conda/files/6435567/Darwin-gfortran.mk.txt)

**Comment by wingtorres** [comment]
From a quick diff it seems the difference is just that in John's .mk file the -lnetcdf and -lnetcdff flags are explicitly spelled out. In my conda environment "nf-config --flibs" already returns -lnetcdf and -lnetcdff so I thought that wouldn't be necessary... anyway,  I'll go ahead and close the ticket now - glad things are working for you!

[diff.txt](https://github.com/wingtorres/coawst-conda/files/6435760/diff.txt)

**Comment by asuanda** [comment]
Hey, just one more thing. In a recent COAWST pull, the NETCDF inc file is
specified in the SCRIP_COAWST makefile.

So, one addition in your great "recipe" to build, could be:

Now in the SCRIP_COAWST directory, make sure to specify in the makefile,
FORT = gfortran, and line 44 is commented out:
*#NETCDF_INCFILE := netcdf.inc *
